### ISSUE TITLE
respect the context

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-tls#2]
The Go standard library doesn't provide any way to use a `Context` when handshaking on pre-dialed TCP connection, see https://github.com/golang/go/issues/18482.

**Comment by marten-seemann** [comment]
I'm not sure if there's a good solution here.
The two obvious methods rely on modifying state of the underlying `net.Conn`:
* closing the connection
* setting read / write deadlines

Closing the connection is undesirable since the application might want to reuse the connection for something else. Setting deadlines is undesirable because there's no way to read a deadline that's already set on the connection, so we'd have to modify the deadline when the context is canceled.

**Comment by marten-seemann** [comment]
@Stebalien What do you think about this? It seems like there's nothing we can do because of the fundamental incompatibility of `io.Reader` and the context.

**Comment by Stebalien** [comment]
I'd close the connection. Once we *start* reading/writing to the connection, there's really no way to recover it without some kind of "cleanup" handshake and some way to signal to the caller that the connection is "clean".

Note: Handling situations like this was one of the goals of the serial-stream multiplexer (in the multistream-2.0 proposal).
