### ISSUE TITLE
use TLS 1.3

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-tls#3]
We have two options here:

1. use tls-tris (with some minimal, trivial modifications, to make it work with the standard Go compiler)
2. wait until the Go standard library adds support for TLS 1.3

Note that adding support for TLS 1.3 is inherently backwards compatible, since TLS handles version negotiation itself.

**Comment by raulk** [comment]
Go master includes TLS 1.3 support, but with some features like 0-RTT missing and not making it for Go 1.12.

https://github.com/golang/go/commit/30cc9780856b5a88ca2a8f05312758077ca48ba1

Does it make sense to develop this repo against master until 1.12 comes out?

**Comment by marten-seemann** [comment]
> Go master includes TLS 1.3 support, but with some features like 0-RTT missing and not making it for Go 1.12.

Wonderful, I hadn't seen that so far! I don't really care about 0-RTT at this point, but this is really good news security-wise, as well as performance-wise (the TLS 1.3 handshake is 1 RTT faster than TLS 1.2).
This means that the payoff of using tls-tris is probably too small to justify the effort.

> Does it make sense to develop this repo against master until 1.12 comes out?

If we want to deploy TLS 1.3 asap, that would require us to build releases against *tip*, and I'd be a bit worried about stability.
If we want to start phasing out secio as quickly as possible, we should start using TLS 1.2 now, and we'll get one round trip for free as soon as we build the first release using Go 1.12.

**Comment by raulk** [comment]
Makes sense, @marten-seemann.

**Comment by marten-seemann** [comment]
Update: TLS 1.3 was made opt-in for Go 1.12, and will become default with Go 1.13, see
https://github.com/golang/go/issues/30055 and https://github.com/golang/go/commit/5d9bc60893d66073ca82eecee7c9800321535f52#diff-0977a3b43ae53839ce25d758f24138f2.

It's activated via a GODEBUG flag. We can hack our way around this by manually setting this variable via `os.Setenv`.
