### ISSUE TITLE
share handshaking logic with QUIC

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-tls#4]
Related issue: https://github.com/libp2p/go-libp2p-quic-transport/issues/18.

The handshake logic is basically the same as in https://github.com/libp2p/go-libp2p-quic-transport/tree/identity.

**Comment by Stebalien** [comment]
Would it make sense to just make the quic transport depend on this package? It'll pull in some extra code but that would mean we wouldn't need an additional repo.

**Comment by marten-seemann** [comment]
Sounds reasonable. I just saw that I already exposed those functions, so we might even be able to do this without any further changes to this repo.

**Comment by marten-seemann** [comment]
Fixed by https://github.com/libp2p/go-libp2p-quic-transport/pull/67.
