### ISSUE TITLE
crypto.go:217:20: undefined: cpu.S390X

### ISSUE THREAD

**Issue by mobileink** [libp2p/go-libp2p-tls#66]
Hi.  I'm trying to compile go-libp2p using Bazel, and I'm stuck on this error.  It looks to me like this actually is defined, at least in https://godoc.org/golang.org/x/sys/cpu, which my build appears to be using. I'm afraid I'm not very familiar with Go; can you offer any advice?  FWIW the Bazel output is below.

Thanks, gregg

 (cd /private/var/tmp/_bazel_gar/29372927b20ca936dc9ab48a0d65e05d/sandbox/darwin-sandbox/502/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    CGO_ENABLED=1 \
    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
    GOARCH=amd64 \
    GOOS=darwin \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=external/local_config_cc:/bin:/usr/bin \
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk \
    TMPDIR=/var/folders/wz/dx0cgvqx5qn802qmc3d4hcfr0000gp/T/ \
    XCODE_VERSION_OVERRIDE=11.4.1.11E503a \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_gar/29372927b20ca936dc9ab48a0d65e05d/sandbox/darwin-sandbox/502/sandbox.sb /var/tmp/_bazel_gar/install/1d6d7a22a62da56414387a04bacbf619/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_github_libp2p_go_libp2p_tls/conn.go -src external/com_github_libp2p_go_libp2p_tls/crypto.go -src external/com_github_libp2p_go_libp2p_tls/extension.go -src external/com_github_libp2p_go_libp2p_tls/transport.go -arc 'github.com/libp2p/go-libp2p-core/crypto=github.com/libp2p/go-libp2p-core/crypto=bazel-out/darwin-fastbuild/bin/external/com_github_libp2p_go_libp2p_core/crypto/go_default_library.a=' -arc 'github.com/libp2p/go-libp2p-core/peer=github.com/libp2p/go-libp2p-core/peer=bazel-out/darwin-fastbuild/bin/external/com_github_libp2p_go_libp2p_core/peer/go_default_library.a=' -arc 'github.com/libp2p/go-libp2p-core/sec=github.com/libp2p/go-libp2p-core/sec=bazel-out/darwin-fastbuild/bin/external/com_github_libp2p_go_libp2p_core/sec/go_default_library.a=' -arc 'golang.org/x/sys/cpu=golang.org/x/sys/cpu=bazel-out/darwin-fastbuild/bin/external/org_golang_x_sys/cpu/go_default_library.a=' -importpath github.com/libp2p/go-libp2p-tls -p github.com/libp2p/go-libp2p-tls -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o bazel-out/darwin-fastbuild/bin/external/com_github_libp2p_go_libp2p_tls/go_default_library.a -gcflags '' -asmflags '')
compilepkg: error running subcommand: exit status 2
/private/var/tmp/_bazel_gar/29372927b20ca936dc9ab48a0d65e05d/sandbox/darwin-sandbox/502/execroot/__main__/external/com_github_libp2p_go_libp2p_tls/crypto.go:217:20: undefined: cpu.S390X

**Comment by marten-seemann** [comment]
I'm not familiar with Bazel, you might want to check the Go version you're using.
