### ISSUE TITLE
Does support CA(Certificate Authority)?

### ISSUE THREAD

**Issue by yahtoo** [libp2p/go-libp2p-tls#70]
For example, I want to use libP2P to create a coalition that requires an access mechanism to enter

**Comment by aschmahmann** [comment]
I don't think so. You might want to look at using a private network https://github.com/libp2p/go-libp2p/blob/d4d6adff6e3260792cb4514c27368059f2558530/options.go#L152 or using the general connection gating interface https://github.com/libp2p/go-libp2p/blob/d4d6adff6e3260792cb4514c27368059f2558530/options.go#L387

**Comment by aschmahmann** [comment]
cc @marten-seemann in case you have any thoughts/ideas here.

**Comment by kason-huang** [comment]
https://github.com/libp2p/go-libp2p-tls/blob/master/crypto.go#L79 It seems that we can pass the certificates to the Identity by ourselfs. Can we use this function to support ca?

**Comment by marten-seemann** [comment]
Who would run the CA? The point of a p2p network is to not have a central authority.

**Comment by kason-huang** [comment]
I use libp2p relay and hole-punch capabilities to achieve cross-LAN access, I hope that nodes is mutual authentication, to avoid malicious links and protect the node. I want to use the PrivateNetwork way, but some nodes are not managed by myself, I can not guarantee that the private key is not leaked. So I'd like to see if I can do this certification based on CA.

**Comment by marten-seemann** [comment]
>  I hope that nodes is mutual authentication, to avoid malicious links and protect the node

That is exactly what this library is designed to do.

> I want to use the PrivateNetwork way, but some nodes are not managed by myself, I can not guarantee that the private key is not leaked. So I'd like to see if I can do this certification based on CA.

You can use private networks by sharing a key between all nodes. There's no way to guarantee that a private key hasn't leaked though, no matter if you use a CA or not.

**Comment by marten-seemann** [comment]
Closing this issue. There's nothing actionable here.

**Comment by khalid-davis** [comment]
Hello, what do we need to do in libp2p if our pre-shared keys (private networks) is leaked? Do we need to restart all peers and give them a new pre-shared keys (private networks)?
