### ISSUE TITLE
Fix permissions

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-tls#8]
Needs write access by the go team, admin access by the admin team.

**Comment by marten-seemann** [comment]
Who has the permissions to change the permissions? I checked if I can do anything (since it was me who created this repo), but I can't find anything in the settings.

**Comment by Stebalien** [comment]
Check the "Collaborators & teams" section.

**Comment by marten-seemann** [comment]
Doesn't look like I can do it, seems like this is something that has to be done by the [owners of libp2p](https://github.com/orgs/libp2p/people?query=role%3Aowner). Surprising that you're not one of them.

<img width="1017" alt="screen shot 2018-12-13 at 11 19 35" src="https://user-images.githubusercontent.com/1478487/49916391-03c62900-fec9-11e8-8fa6-2fd089449919.png">

**Comment by Stebalien** [comment]
Click the "Add a team" dropdown.

(and we probably shouldn't have that many owners)

**Comment by marten-seemann** [comment]
Done.

**Comment by Stebalien** [comment]
Thanks!
