### ISSUE TITLE
What was the purpose of introducing NewIdentity

### ISSUE THREAD

**Issue by kason-huang** [libp2p/go-libp2p-tls#89]
What was the purpose of introducing NewIdentity, https://github.com/libp2p/go-libp2p-tls/blob/master/crypto.go#L40? Seems to be using a self-signed certificate for authentication?

**Comment by marten-seemann** [comment]
Please refer to our [specification](https://github.com/libp2p/specs/blob/master/tls/tls.md) for an explanation how authentication works.
