### ISSUE TITLE
[Question] About pre-shared keys

### ISSUE THREAD

**Issue by kason-huang** [libp2p/go-libp2p-tls#90]
Hello, what do we need to do in libp2p if our pre-shared keys (private networks) is leaked? Do we need to restart all peers and give them a new pre-shared keys (private networks)?

**Comment by marten-seemann** [comment]
Please ask questions at https://discuss.libp2p.io/. This is an issue tracker, not a discussion forum (and this question is not even TLS-related to begin with).
