### ISSUE TITLE
how go-libp2p-tls solve the Man-in-the-middle attack

### ISSUE THREAD

**Issue by ghost** [libp2p/go-libp2p-tls#92]

**Comment by khalid-davis** [comment]
https://github.com/libp2p/specs/blob/master/tls/tls.md#peer-authentication，the libp2p-tls will verify the peer identity which need the real public-key, so the man-in-the-middle attack will no work.

**Comment by ghost** [comment]
https://github.com/libp2p/specs/blob/master/tls/tls.md#peer-authentication, it seems that the node will verify the peer Identity according to the real public-key, so the man-in-the-middle attack will no work.
